server:
  port: 8088
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: sqlpw
#可以用data.name表示
data:
  name: "你好"
  age:  30
  gender: 男
