server:
  port: 8088
spring:
    jackson:
      property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url : jdbc:mysql://140.143.xxx:3306/test_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: sqlpw
#可以用data.name表示
qiniu:
    ak: xx
    sk: xx
    bucket: blog_v3